package:
  name: q2-boots
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  host:
  - python {{ python }}
  - pip
  - setuptools
  - versioningit
  - wheel
  run:
  - python {{ python }}
  - numpy {{ numpy }}
  - pandas {{ pandas }}
  - scikit-bio {{ scikit_bio }}
  - hdmedians
  - qiime2 >={{ qiime2 }}
  - q2-types >={{ q2_types }}
  - q2-diversity-lib >={{ q2_diversity_lib }}
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  requires:
  - qiime2 >={{ qiime2 }}
  - q2-types >={{ q2_types }}
  - q2-kmerizer >={{ q2_kmerizer }}
  - q2-diversity >={{ q2_diversity }}
  - q2-feature-table >={{ q2_feature_table }}
  - q2-vizard >={{ q2_vizard }}
  - pytest
  imports:
  - q2_boots
  - qiime2.plugins.boots
  commands:
  - py.test --pyargs q2_boots
about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
