package:
  name: q2-boots
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  build:
  - python {{ python }}
  - nodejs
  - setuptools
  - versioningit
  host:
  - hdmedians
  - python {{ python }}
  - numpy {{ numpy }}
  - pandas {{ pandas }}
  - q2-diversity-lib >={{ q2_diversity_lib }}
  - q2-types >={{ q2_types }}
  - qiime2 >={{ qiime2 }}
  - scikit-bio {{ scikit_bio }}
  - setuptools
  - versioningit
  - wheel
  run:
  - python {{ python }}
  - qiime2 >={{ qiime2 }}
test:
  requires:
  - pytest
  - qiime2 >={{ qiime2 }}
  imports:
  - q2_boots
  - qiime2.plugins.boots
  commands:
  - py.test --pyargs q2_boots
about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
