channels:
- https://packages.qiime2.org/qiime2/latest/amplicon/passed
- conda-forge
- bioconda
dependencies:
  - qiime2-amplicon
  - hdmedians
  - pip
  - pip:
     - q2-kmerizer@git+https://github.com/bokulich-lab/q2-kmerizer.git@main
